name: xref
description: "Cross platform image board app for Windows/MacOS/iOS/Android."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # ui
  google_fonts:
  flutter_box_transform:
  flutter_speed_dial:
  bitsdojo_window:

  # state management
  hooks_riverpod:
  flutter_riverpod:
  riverpod_annotation:
  undo:

  # path resolve
  image_size_getter:
  path:
  path_provider:
  http:
  mime:
  uuid:

  # l10n
  flutter_localizations:
    sdk: flutter
  intl: any
  image_picker:

dev_dependencies:
  # flutter
  flutter_test:
    sdk: flutter
  flutter_lints:

  # generator
  build_runner:
  riverpod_generator:

  sqflite:

flutter:
  uses-material-design: true
  assets:
    - assets/icon.png

flutter_intl:
  enabled: true
