name: xref
description: "Cross platform image board app for Windows/MacOS/iOS/Android."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_box_transform: ^0.4.2
  image_size_getter: ^2.1.2
  undo: ^1.5.0
  flutter_speed_dial: ^7.0.0
  image_picker: ^1.0.5
  bitsdojo_window: ^0.1.6
  path_provider: ^2.1.1
  http: ^1.1.2
  mime: ^1.0.4
  uuid: ^4.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - images/image.png
